execute pathogen#infect()
syntax on
filetype plugin indent on

" show existing tab with 4 spaces width
set tabstop=4

" when indenting with '>', use 4 spaces width
set shiftwidth=4

" On pressing tab, insert 4 spaces
set expandtab

" Disable haskell indent
let g:haskell_indent_disable = 1
let g:purescript_indent_disable = 1
