# .xinitrc

xrandr --setprovideroutputsourcemodesetting NVIDIA-0
xrandr --auto

xrdb $HOME/.Xresources
xsetroot -cursor_name left_ptr
xsetroot -solid '#80a0af'

# if we have private ssh key(s), start ssh-agent and add the key(s)
id=$HOME/.ssh/id_rsa
if [ -x /usr/bin/ssh-agent ] && [ -f $id ]; then
  eval `ssh-agent -s`
  ssh-add < /dev/null
fi

setxkbmap fi

xmodmap -e "keycode 233 = Page_Down"
xmodmap -e "keycode 234 = Page_Up"
xmodmap -e "remove Lock = Caps_Lock"
xmodmap -e "keysym Caps_Lock = Control_L"
xmodmap -e "add Control = Control_L"

export PATH="$PATH:/home/otto/bin"

xautolock -time 5 -locker slock &

dzconky &

exec xmonad
