# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

set _JAVA_AWT_WM_NONREPARENTING=1